# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 15:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='award',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='company',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='design_design_software',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='design_portfolio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='dev_exp',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='dev_short_blub',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='dev_what_you_want_to_learn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2016, 3, 14, 15, 56, 12, 712250, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='gpa',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='interest',
            field=models.TextField(default='None'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='intern_type',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='major',
            field=models.CharField(default='none', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='message_id',
            field=models.CharField(default='None', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='mkt_advertising_platforms_or_marketing_tools',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='mkt_fav_brand',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='mkt_short_blub',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='name',
            field=models.CharField(default='None', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='po_biz_idea',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='po_fav_startup',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='po_more_interesting',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='po_platform_tools',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='po_short_blub',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='posistion',
            field=models.CharField(default='None', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='semester_year',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2016, 3, 14, 15, 57, 38, 661726, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='technical_skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='tel',
            field=models.CharField(default='0812345678', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='university',
            field=models.CharField(default='None', max_length=250),
            preserve_default=False,
        ),
    ]
