# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 02:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20160314_1929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='posistion',
            new_name='position',
        ),
    ]
