# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='score_designer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='score_mkt_po',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='score_se_qa',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
